services:
  - type: web
    name: trip-gpt
    env: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: TAVILY_API_KEY
        sync: false
      - key: AVIATIONSTACK_API_KEY
        sync: false
